### PR TITLE
Parquet tfxio

### PR DESCRIPTION
**Pull request by martinbomio**
Reopening https://github.com/tensorflow/tfx-bsl/pull/52 since the changes were deleted in https://github.com/tensorflow/tfx-bsl/commit/017c17b3db269e9693f5e234069873e6e748b0dc

### CODE REVIEW

**Comment by martinbomio** [comment]
cc @iindyk

**Review by iindyk — APPROVED** [review]

**Comment by martinbomio** [comment]
@iindyk any chance we can merge this one soon and release a new version so I can implement the rest of the changes in TFX repo?

**Comment by iindyk** [comment]
Also, I don't think you'll have to wait for the release for TFX changes, we release in a train and TFX release is after tfx_bsl release

**Comment by iindyk** [comment]
actually yeah, the tfx changes will need to be merged in a window when tfx-bsl is released and tfx - not yet. I (with help from @jay90099) will make sure to merge before the tfx is released if the changes are going to be ready

**Pull request merged**
